//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSidePagingExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int position_id { get; set; }
        public int office_id { get; set; }
        public string sex { get; set; }
        public int age { get; set; }
        public System.DateTime start_date { get; set; }
        public decimal salary { get; set; }
        public System.DateTime updated_utc { get; set; }
    }
}
